stages:
  - build
  - test

build_pipeline:
  image: condaforge/mambaforge:23.3.1-0
  stage: build
  script:
    - mamba env create -f environment.yml --prefix conda_env/
    - source /opt/conda/bin/activate conda_env/
    - pip install .

test_pipeline:
  image: condaforge/mambaforge:23.3.1-0
  stage: test
  script:
    - mamba env create -f environment.yml --prefix conda_env/
    - source /opt/conda/bin/activate conda_env/
    - pip install .
    - python -m unittest tests/tests.py
    - bash run_test.sh

