stages:
  - build
  - test

build_pipeline:
  image: condaforge/mambaforge:23.3.1-0
  stage: build
  script:
    - mamba env create -f environment.yml --prefix conda_env/
    - source /opt/conda/bin/activate conda_env/
    - pip install .

test_pipeline:
  image: condaforge/mambaforge:23.3.1-0
  stage: test
  script:
    - mamba env create -f environment.yml --prefix conda_env/
    - source /opt/conda/bin/activate conda_env/
    - pip install .
    - python -m unittest tests/test_alignment_info.py
    - python -m unittest tests/test_coverage.py
    - python -m unittest tests/test_io_methods.py
    - python -m unittest tests/test_read_classification.py
    - python -m unittest tests/test_read_processing.py
    - python -m unittest tests/test_seq_table.py
    - bash run_test.sh
