stages:
  - test
  - deploy

test_pipeline:
  image: condaforge/mambaforge:23.3.1-0
  stage: test
  script:
    - mamba env create -f environment.yml --prefix conda_env/
    - source /opt/conda/bin/activate conda_env/
    - pip install .
    - python -m unittest tests/tests.py
    - bash run_test.sh

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
