name: bpquant
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - bowtie2=2.5.3
  - bwa=0.7.17
  - samtools=1.9
  - pysam=0.21.0
  - star=2.7.8a
  - pip
  - pip:
    - build
    - twine
